// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class GoogleTestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void googleTest() {
    // Test name: GoogleTest
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.Navigate().GoToUrl("https://www.google.com/");
    // 2 | setWindowSize | 1423x766 |  | 
    driver.Manage().Window.Size = new System.Drawing.Size(1423, 766);
    // 3 | click | css=center:nth-child(1) > .RNmpXc |  | 
    driver.FindElement(By.CssSelector("center:nth-child(1) > .RNmpXc")).Click();
    // 4 | click | id=searchinput |  | 
    driver.FindElement(By.Id("searchinput")).Click();
    // 5 | type | id=searchinput | Malaysia | 
    driver.FindElement(By.Id("searchinput")).SendKeys("Malaysia");
    // 6 | sendKeys | id=searchinput | ${KEY_ENTER} | 
    driver.FindElement(By.Id("searchinput")).SendKeys(Keys.Enter);
    // 7 | click | linkText=Hari Merdeka 2019 |  | 
    driver.FindElement(By.LinkText("Hari Merdeka 2019")).Click();
  }
}
